InteraktifBilgiEkranı/Controllers/TvController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InteraktifBilgiEkranı.Controllers
{
    public class TvController : Controller
    {
        TvManager Tm = new TvManager(new EfTvDAL());
        DepartmentManager Dm = new DepartmentManager(new EfDepartmentDAL());
        UserManager Um = new UserManager(new EfUserDAL());
        Context c = new Context();
        [HttpGet]
        [Authorize(Roles="ADM,TEK")]
        public ActionResult Index()
        {
            string p = (string)Session["UserMail"];
            int id = c.Users.Where(x => x.UserMail == p).Select(y => y.UserID).FirstOrDefault();
            var userValues = Um.GetByID(id);
            string path = userValues.UserPath;
            TempData["Path"] = path;

            var tvValues = Tm.GetList();
            return View(tvValues);
        }

        [HttpGet]
        [Authorize(Roles = "ADM,TEK")]
        public ActionResult AddTv()
        {
            string p = (string)Session["UserMail"];
            int id = c.Users.Where(x => x.UserMail == p).Select(y => y.UserID).FirstOrDefault();
            var userValues = Um.GetByID(id);
            string path = userValues.UserPath;
            TempData["Path"] = path;

            List<SelectListItem> valueDepartment = (from x in Dm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.DepartmentName,
                                                     Value = x.DepartmentID.ToString()
                                                 }
                                                 ).ToList();
            ViewBag.vld = valueDepartment;
            return View();
        }

        [HttpPost]
        public ActionResult AddTv(Tv p)
        {
            Tm.TvAdd(p);
            return RedirectToAction("Index");

        }

        [HttpGet]
        [Authorize(Roles = "ADM,TEK")]
        public ActionResult EditTv(int id)
        {
            string p = (string)Session["UserMail"];
            int idd = c.Users.Where(x => x.UserMail == p).Select(y => y.UserID).FirstOrDefault();
            var userValues = Um.GetByID(idd);
            string path = userValues.UserPath;
            TempData["Path"] = path;

            List<SelectListItem> valueDepartment = (from x in Dm.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.DepartmentName,
                                                     Value = x.DepartmentID.ToString()
                                                 }
                                                  ).ToList();
            ViewBag.vld = valueDepartment;
            var tvValues = Tm.GetByID(id);
            return View(tvValues);
        }
        [HttpPost]
        public ActionResult EditTv(Tv p)
        {
            p.TvStatus = true;
            Tm.TvUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteTv(int id)
        {
            var tvValues = Tm.GetByID(id);
            Tm.TvDelete(tvValues);
            return RedirectToAction("Index");
        }

        public ActionResult ChangeStatusTv(int id)
        {
            var tvValues = Tm.GetByID(id);
            Tm.TvChangeStatus(tvValues);
            return RedirectToAction("Index");
        }

        public ActionResult ReportTv()
        {
            ViewBag.title = "Ekran Raporlama Sayfası";
            var tvValues = Tm.GetList();
            return View(tvValues);
        }
    }
}

InteraktifBilgiEkranı/Views/Tv/AddTv.cshtml
@model EntityLayer.Concrete.Tv
@{
    ViewBag.Title = "AddTv";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("AddTv", "Tv", FormMethod.Post))
{
    <div class="col-md-12" style="width: 450px">
        <div class="card-body">
            <p class="mb-2"><strong>Ekran Ekleme Sayfası</strong></p>
            <br />

            <div class="form-group mb-3">
                @Html.Label("Ekran Açıklaması")
                @Html.TextBoxFor(x => x.TvDescription, new { @class = "form-control" })
            </div>

            <div class="form-group mb-3">
                @Html.Label("Ekran Adresi")
                @Html.TextBoxFor(x => x.TvAddress, new { @class = "form-control" })
            </div>

            <div class="form-group mb-3">
                @Html.Label("Ekran Yaratılış Tarihi")
                @Html.TextBoxFor(x => x.TvCreationDate, new { @class = "form-control", @placeholder = "gg.aa.yyyy" })
            </div>


            <div class="form-group mb-3">
                @Html.Label("Ekran Durumu")
                <br />
                @Html.RadioButtonFor(x => x.TvStatus, "True")@Html.Label("Aktif")
                <br />
                @Html.RadioButtonFor(x => x.TvStatus, "False")@Html.Label("Pasif")
            </div>

            <div class="form-group mb-3">
                @Html.Label("Bağlı Olduğu Bölüm")
                @Html.DropDownListFor(x => x.DepartmentID, (List<SelectListItem>)ViewBag.vld, new
                { @class = "form-control" })
            </div>
            <button class="btn btn-primary">Kaydet</button>
            <a href="/Tv/Index" class="btn btn-primary m-md-2">Geri Git</a>
        </div>
    </div>
}

InteraktifBilgiEkranı/Views/Tv/EditTv.cshtml
@model EntityLayer.Concrete.Tv
@{
    ViewBag.Title = "EditTv";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("EditTv", "Tv", FormMethod.Post))
{
    <div class="col-md-12" style="width: 450px">
        <div class="card-body">
            <p class="mb-2"><strong>Ekran Güncelleme Sayfası</strong></p>
            <br />

            @Html.HiddenFor(model => model.TvID)

            @*<div class="form-group mb-3">
            @Html.Label("Tv ID")
            @Html.TextBoxFor(x => x.TvID, new { @class = "form-control" })
        </div>*@

            <div class="form-group mb-3">
                @Html.Label("Ekran Açıklaması")
                @Html.TextBoxFor(x => x.TvDescription, new { @class = "form-control" })
            </div>

            <div class="form-group mb-3">
                @Html.Label("Ekran Adresi")
                @Html.TextBoxFor(x => x.TvAddress, new { @class = "form-control" })
            </div>

            <div class="form-group mb-3">
                @Html.Label("Ekran Yaratılış Tarihi")
                @Html.TextBoxFor(x => x.TvCreationDate, Model.TvCreationDate.ToString("dd.MM.yyyy"), new { @class = "form-control" })
            </div>

            <div class="form-group mb-3">
                @Html.Label("Bağlı Olduğu Bölüm")
                @Html.DropDownListFor(x => x.DepartmentID, (List<SelectListItem>)ViewBag.vld,
                new { @class = "form-control" })
            </div>
            <button class="btn btn-primary">Güncelle</button>
            <a href="/Tv/Index" class="btn btn-primary m-md-2">Geri Git</a>
        </div>
    </div>
}

InteraktifBilgiEkranı/Views/Tv/Index.cshtml
@using EntityLayer.Concrete
@model List<Tv>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    string checkStatus = "";
    string buttonStatusColor = "";
    string badgeStatusColor = "";
    string tvStatus = "";
}
<br />

<div class="col-md-12 my-auto">
    <h2>Ekran Yönetim Sayfası</h2>
    <br />

    <div>
        <table class="table table-bordered table-hover mb-0">
            <tr>
                @*<th>#</th>*@
                <th>Açıklama</th>
                <th>Adres</th>
                <th>Tarih</th>
                <th>Durum</th>
                <th>Bölüm</th>
                <th>Güncelle</th>
                <th>Aktif/Pasif</th>
                <th>Sil</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>@item.TvID</td>*@
                    <td>@item.TvDescription</td>
                    <td>@item.TvAddress</td>
                    <td>
                        <div class="time-label">
                            <span>@(((DateTime)item.TvCreationDate).ToString("dd.MM.yyyy"))</span>
                        </div>
                    </td>
                    <td>
                        @switch (item.TvStatus)
                        {
                            case true:
                                badgeStatusColor = "badge badge-success";
                                buttonStatusColor = "btn btn-warning";
                                tvStatus = "Aktif Durum";
                                break;
                            case false:
                                badgeStatusColor = "badge badge-warning";
                                buttonStatusColor = "btn btn-success";
                                tvStatus = "Pasif Durum";
                                break;
                        }
                        <span class="@badgeStatusColor">@tvStatus</span>
                    </td>
                    <td>@item.Department.DepartmentName</td>
                    <td><a href="/Tv/EditTv/@item.TvID" class="btn btn-info">Güncelle</a></td>
                    <td>
                        <a class="@buttonStatusColor" href="/Tv/ChangeStatusTv/@item.TvID">

                            @if (item.TvStatus == true)
                            {
                                checkStatus = "Pasif Yap";
                            }
                            else
                            {
                                checkStatus = "Aktif Yap";
                            }
                            @checkStatus

                        </a>
                    </td>
                    <td><a href="/Tv/DeleteTv/@item.TvID" class="btn btn-danger">Sil</a></td>
                </tr>
            }
        </table>
    </div>
    <br />
    <a href="/Tv/AddTv" class="btn btn-primary">Yeni Ekran Yarat</a>
    <a href="/Tv/ReportTv" class="btn btn-primary m-md-2">Rapor</a>
</div>

InteraktifBilgiEkranı/Views/Tv/ReportTv.cshtml
@using EntityLayer.Concrete
@model List<Tv>
@{
    Layout = null;
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="margin-left:10px; width:99%">
        <thead>
            <tr>
                <th>#</th>
                <th>Açıklama</th>
                <th>Adres</th>
                <th>Tarih</th>
                <th>Durum</th>
                <th>Bölüm</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.TvID</td>
                    <td>@item.TvDescription</td>
                    <td>@item.TvAddress</td>
                    <td>
                        <div class="time-label">
                            <span>@(((DateTime)item.TvCreationDate).ToString("dd-MM-yyyy"))</span>
                        </div>
                    </td>
                    <td>@item.TvStatus</td>
                    <td>@item.Department.DepartmentName</td>
                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>
</body>
</html>